=== projectestac/merli/semanticnet/source/semanticNetv3.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by aleix canals (docum) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="semanticNet">
		<xs:annotation>
			<xs:documentation>Descripció de les propietats de la xarxa</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Nom identificador de la xarxa</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Pot haver-hi un, cap o diversos DataSource's descrits.</xs:documentation>
					</xs:annotation>
					<xs:element ref="dataSource" minOccurs="0"/>
				</xs:sequence>
				<xs:element name="relations">
					<xs:annotation>
						<xs:documentation>Descripció del tipus de relacions que conté la xarxa</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="relation">
								<xs:complexType>
									<xs:all>
										<xs:element name="type" type="xs:string">
											<xs:annotation>
												<xs:documentation>Tipus identificador de la relacio.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="description" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Descripció de la relació.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="properties" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="nodes">
					<xs:annotation>
						<xs:documentation>Descripció del tipus de nodes que conté la xarxa</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="node">
								<xs:complexType>
									<xs:all>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="description" type="xs:string" minOccurs="0"/>
										<xs:element ref="properties" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="propertiesType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="property">
				<xs:complexType>
					<xs:all>
						<xs:element name="name" type="xs:string">
							<xs:annotation>
								<xs:documentation>Nom de la propietat.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="value" type="xs:string">
							<xs:annotation>
								<xs:documentation>valor de la propietat.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="properties" type="propertiesType"/>
	<xs:element name="dataSource">
		<xs:annotation>
			<xs:documentation>Informació necessaria per inicialitzar el repositori de dades.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="class" type="xs:string">
					<xs:annotation>
						<xs:documentation>Classe utilitzada per implementar el Repositori de dades.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="properties" minOccurs="0"/>
				<xs:element name="dynamic" type="xs:boolean" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Indica si la xarxa s'ha de carregar de forma dinàmica o no.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="relations">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="relationType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="nodes">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="nodeType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== projectestac/merli/semanticnet/source/curriculumFulletiq.xml
<?xml version="1.0" encoding="ISO-8859-1"?><semanticNet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="semanticNetv3.xsd">	<dataSource>	<dynamic>false</dynamic>		<class>edu.xtec.merli.semanticnet.nouDataSourceTHJDBC</class>		<relations>		<relationType>MT</relationType>		<relationType>BT</relationType>		<relationType>RT</relationType>		<relationType>USE</relationType>		<relationType>UF</relationType>		<relationType>RBT</relationType>		<relationType>OT</relationType>		</relations>		<nodes>		<nodeType>thesaurus</nodeType>		</nodes>	</dataSource>	<dataSource>		<dynamic>false</dynamic>		<class>edu.xtec.merli.semanticnet.nouDataSourceSNJDBC</class>		<relations>		<relationType>RCL</relationType>		<relationType>RCA</relationType>		<relationType>RCC</relationType>		<relationType>ROL</relationType>		<relationType>ROA</relationType>		<relationType>RAL</relationType>		<relationType>RLL</relationType>		<relationType>RH</relationType>		<relationType>RN</relationType>		<relationType>RET</relationType>		</relations>		<nodes>		<nodeType>level</nodeType>		<nodeType>area</nodeType>		<nodeType>objective</nodeType>		<nodeType>content</nodeType>		<nodeType>notes</nodeType>		<nodeType>history</nodeType>		</nodes>	</dataSource>	<relations>		<relation>			<type>RT</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>MT</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>BT</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>USE</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation> 		<relation>			<type>UF</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation> 		<relation>			<type>RBT</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>OT</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation><relation>			<type>RCL</type>			<description>Relations objective Content</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RCA</type>			<description>Related area-content</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RCC</type>			<description>Related content-content</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>ROL</type>			<description>Relations level objective</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>ROA</type>			<description>Relations area-objective</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RAL</type>			<description>Relations level-area</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RLL</type>			<description>Relations level-level</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RH</type>			<description>Related history</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RN</type>			<description>Related Notes, observations</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>		<relation>			<type>RET</type>			<description>relation curriculum element - thesaurus</description>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumRelation</value>				</property>			</properties>		</relation>	</relations>	<nodes>		<node>			<type>level</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>area</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>content</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>objective</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>history</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>notes</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.merli.semanticnet.elements.CurriculumNode</value>				</property>			</properties>		</node>		<node>			<type>thesaurus</type>			<properties>				<property>					<name>class</name>					<value>edu.xtec.semanticnet.thesaurus.NodeTypeThesaurus</value>				</property>			</properties>		</node>	</nodes></semanticNet>
